-- Generated by tools/migrate-sheet.mjs — do not edit by hand.
-- Run this in the Supabase SQL editor AFTER supabase-setup.sql.

begin;

delete from ft_stories;
delete from ft_relations;
delete from ft_people;

insert into ft_people (id, name, family, maiden_name, born_family, gender, role, born, died, location, photo_url, bio) values
  ('W01', 'Yash Watwani', 'watwani', null, 'watwani', null, null, 1995, null, 'Gwalior', null, null),
  ('W02', 'Hitanshi Watwani', 'watwani', null, 'watwani', null, null, 2000, null, 'Gwalior', null, null),
  ('W03', 'Amar Watwani', 'watwani', null, 'watwani', null, null, 1970, null, 'Gwalior', null, null),
  ('W04', 'Reema Watwani', 'watwani', 'Reeta', 'sidhwani', null, null, 1975, null, 'Gwalior', null, null),
  ('W05', 'Piyush Watwani', 'watwani', null, 'watwani', null, null, 2008, null, 'Gwalior', null, null),
  ('W06', 'Manoj Watwani', 'watwani', null, 'watwani', null, null, null, 2020, 'Gwalior', null, null),
  ('W07', 'Vaishali Watwani', 'watwani', null, 'watwani', null, null, null, null, 'Gwalior', null, null),
  ('W08', 'Archie Watwani', 'watwani', null, 'watwani', null, null, 2003, null, 'Gwalior', null, null),
  ('W09', 'Komal Watwani', 'watwani', null, 'watwani', null, null, null, null, 'Gwalior', null, null),
  ('W10', 'Shiv Watwani', 'watwani', null, 'watwani', null, null, 1972, 2024, 'Gwalior', null, null),
  ('W11', 'Ankit Watwani', 'watwani', null, 'watwani', null, null, 1995, null, 'Gwalior', null, null),
  ('W12', 'Rahul Watwani', 'watwani', null, 'watwani', null, null, null, 2014, 'Gwalior', null, null),
  ('W13', 'Narayan Das Watwani', 'watwani', null, 'watwani', null, null, null, null, 'Gwalior', null, null),
  ('W14', 'Savitri Watwani', 'watwani', null, 'watwani', null, null, null, null, 'Gwalior', null, null),
  ('W15', 'Divisha Watwani', 'watwani', 'Honey', 'makrani', null, null, 1997, null, 'Gwalior', null, null),
  ('M01', 'Mamta Makrani', 'makrani', null, 'makrani', null, null, null, null, 'Gwalior', null, null),
  ('M02', 'Laxman Makrani', 'makrani', null, 'makrani', null, null, null, null, 'Gwalior', null, null),
  ('M03', 'Nikhil Makrani', 'makrani', null, 'makrani', null, null, null, null, 'Gwalior', null, null),
  ('S01', 'Rajesh Sidhwani', 'sidhwani', null, 'sidhwani', null, null, null, null, 'Banda', null, null),
  ('S02', 'Neha Sidhwani', 'sidhwani', null, 'sidhwani', null, null, null, null, 'Banda', null, null),
  ('S03', 'Kanika Sidhwani', 'sidhwani', null, 'sidhwani', null, null, null, null, 'Banda', null, null),
  ('S04', 'Bhumika Sidhwani', 'sidhwani', null, 'sidhwani', null, null, null, null, 'Banda', null, null),
  ('S05', 'Bhavika Sidhwani', 'sidhwani', null, 'sidhwani', null, null, null, null, 'Banda', null, null);

insert into ft_relations (person_a, person_b, type, year) values
  ('W03', 'W01', 'parent', null),
  ('W03', 'W02', 'parent', null),
  ('W03', 'W04', 'spouse', 1994),
  ('W04', 'W01', 'parent', null),
  ('W04', 'W02', 'parent', null),
  ('W13', 'W03', 'parent', null),
  ('W14', 'W03', 'parent', null),
  ('W13', 'W06', 'parent', null),
  ('W14', 'W06', 'parent', null),
  ('W13', 'W10', 'parent', null),
  ('W14', 'W10', 'parent', null),
  ('W13', 'W14', 'spouse', null),
  ('W10', 'W11', 'parent', null),
  ('W09', 'W11', 'parent', null),
  ('W10', 'W12', 'parent', null),
  ('W09', 'W12', 'parent', null),
  ('W09', 'W10', 'spouse', 1994),
  ('W06', 'W05', 'parent', null),
  ('W07', 'W08', 'parent', null),
  ('W06', 'W07', 'spouse', 2003),
  ('W01', 'W15', 'spouse', 2025);

commit;
